//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizze
    {
        public int Id { get; set; }
        public string NazwaPizzy { get; set; }
        public string Ilosc { get; set; }
        public string CenaJednostkowa { get; set; }
        public string Składniki { get; set; }
    }
}
